version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: hrm_db
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3309:3306"   # for workbench
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: spring_app
    ports:
      - "9009:9009"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/hrm_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
      SERVER_PORT: 9009

volumes:
  mysql_data: